name: Iris MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc==3.51.2 flake8 pytest
        pip install dvc==3.51.2 flake8 pytest
      # Initialize DVC
    - name: Initialize DVC
      run: |
        dvc init --no-scm
        dvc add data/raw/iris.csv
        dvc repro
        ls -a .dvc
        cat dvc.yaml
        ls data/raw/iris.csv.dvc
    # Load data
    - name: Load data
      run: python src/data_loader.py

    # Preprocess data
    - name: Preprocess data
      run: python src/data_preparation.py
        # Clean MLflow artifacts
    - name: Clean MLflow artifacts
      run: |
        rm -rf mlruns mlruns.db mlruns_backup.db
        echo "Cleaned mlruns/ and mlruns.db"

    # Train models
    - name: Train models
      env:
        MLFLOW_TRACKING_URI: sqlite:///mlruns.db
      run: |
        echo "MLflow tracking URI: $MLFLOW_TRACKING_URI"
        echo "MLflow artifact root: $MLFLOW_ARTIFACT_ROOT"
        ls -la
        mlflow ui --port 5000 &
        sleep 5  # Wait for MLflow server to start
        python src/model_train.py

    # Evaluate and register models
    - name: Evaluate and register models
      env:
        MLFLOW_TRACKING_URI: sqlite:///mlruns.db
      run: |
        echo "MLflow tracking URI: $MLFLOW_TRACKING_URI"
        echo "MLflow artifact root: $MLFLOW_ARTIFACT_ROOT"
        ls -la mlruns
        python src/model_evaluate.py

    # Build Docker image
    - name: Build Docker image
      run: 
        docker build -t iris-mlops-api .
        # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      env:
        DOCKERHUB_USERNAME: 2023ad05044
        DOCKERHUB_TOKEN: dckr_pat_ZsbAqQTXSNFeiXwjffrrhCGI39g
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker tag iris-mlops-api $DOCKERHUB_USERNAME/iris-mlops-api:latest
        docker push $DOCKERHUB_USERNAME/iris-mlops-api:latest

    # Run Docker container
    - name: Run Docker container
      run: docker run -d -p 8000:8000 iris-mlops-api

    # Test API and log prediction
    - name: Test API and log prediction
      run: |
        sleep 5  # Wait for container to start
        curl -X POST "http://localhost:8000/predict" -H "Content-Type: application/json" -d '{"features": [5.1, 3.5, 1.4, 0.2]}' > prediction.json
        python -c "import json; import pandas as pd; import os; from datetime import datetime; data = json.load(open('prediction.json')); log_entry = {'timestamp': datetime.now().isoformat(), 'features': [5.1, 3.5, 1.4, 0.2], 'prediction': data['prediction']}; log_df = pd.DataFrame([log_entry]); os.makedirs('logs', exist_ok=True); log_df.to_csv('logs/predictions.csv', index=False)"
    # Test metrics endpoint
    - name: Test metrics endpoint
      run: |
        curl http://localhost:8000/metrics
    # Upload prediction logs as artifact
    - name: Upload prediction logs
      uses: actions/upload-artifact@v4
      with:
        name: prediction-logs
        path: logs/predictions.csv
        if-no-files-found: warn
        include-hidden-files: false

    # Upload saved models as artifact
    - name: Upload saved models
      uses: actions/upload-artifact@v4
      with:
        name: saved-models
        path: saved_models/
        if-no-files-found: warn
        include-hidden-files: false

    # Upload MLflow artifacts
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/
        if-no-files-found: warn
        include-hidden-files: false
       # Upload DVC artifacts
    - name: Upload DVC artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dvc-artifacts
        path: |
          .dvc
          dvc.yaml
          data/raw/iris.csv.dvc
        if-no-files-found: warn
        include-hidden-files: true